[{$smarty.block.parent}]
[{*block weight*}]
[{if $oDetailsProduct->oxarticles__swabtropfgewicht->value}]
    <br>[{oxmultilang ident="ABTROPFGEWICHT"}]: [{$oDetailsProduct->oxarticles__swabtropfgewicht->value}][{oxmultilang ident="UNIT_G"}]
[{/if}]
[{*Zuratenliste in Produktdetails*}]
[{*if $oDetailsProduct->oxarticles__swingredients->value}]
    <br>[{oxmultilang ident="INGREDIENTS"}]: [{$oDetailsProduct->oxarticles__swingredients->value}]
[{/if*}]